# fly.toml app configuration file generated for chief-of-flow-api on 2025-06-12T10:17:16-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chief-of-flow-api'
primary_region = 'sjc'

[build]

[env]
  API_V1_STR = '/api/v1'
  APP_NAME = 'Chief-of-Flow'
  LOG_LEVEL = 'INFO'
  PORT = '8000'

[processes]
  app = 'uvicorn app.main:app --host 0.0.0.0 --port 8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/v1/health/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
